version: "3"

services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  
  rqworker:
    image: api
    env_file:
      - .env
    environment:
      CRYPTO_CLIENT_BASE_URL: ${CRYPTO_CLIENT_BASE_URL:-https://hiring.api.synthesia.io}
      CRYPTO_CLIENT_TIMEOUT_SECONDS: ${CRYPTO_CLIENT_TIMEOUT_SECONDS:-1.5}
      CRYPTO_CLIENT_RATE_LIMITING_ENABLED: ${CRYPTO_CLIENT_RATE_LIMITING_ENABLED:-false}
      CRYPTO_CLIENT_RATE_LIMIT_PER_MINUTE: ${CRYPTO_CLIENT_RATE_LIMIT_PER_MINUTE:-5}
      REDIS_QUEUE_URL: ${REDIS_QUEUE_URL:-redis://redis:6379/0}
      REDIS_QUEUE_NAME: ${REDIS_QUEUE_NAME:-callback_queue}
      CALLBACK_ENABLED: ${CALLBACK_ENABLED:-true}
      CALLBACK_MAX_UPSTREAM_EVENTS: ${CALLBACK_MAX_UPSTREAM_EVENTS:-10}
      CALLBACK_MAX_RETRY_COUNT: ${CALLBACK_MAX_RETRY_COUNT:-10}
      CALLBACK_ENQUEUE_DELAY_SECONDS: ${CALLBACK_ENQUEUE_DELAY_SECONDS:-20}
      CALLBACK_TIMEOUT_SECONDS: ${CALLBACK_TIMEOUT_SECONDS:-10}
    depends_on:
      - redis
    command: 'python main.py'
    volumes:
      - .:/api/

  rqscheduler:
    image: api
    depends_on:
      - redis
    command: 'rqscheduler --host redis --port 6379 --db 0'
    volumes:
      - .:/api/

  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CRYPTO_CLIENT_BASE_URL: ${CRYPTO_CLIENT_BASE_URL:-https://hiring.api.synthesia.io}
      CRYPTO_CLIENT_TIMEOUT_SECONDS: ${CRYPTO_CLIENT_TIMEOUT_SECONDS:-1.5}
      CRYPTO_CLIENT_RATE_LIMITING_ENABLED: ${CRYPTO_CLIENT_RATE_LIMITING_ENABLED:-false}
      CRYPTO_CLIENT_RATE_LIMIT_PER_MINUTE: ${CRYPTO_CLIENT_RATE_LIMIT_PER_MINUTE:-5}
      REDIS_QUEUE_URL: ${REDIS_QUEUE_URL:-redis://redis:6379/0}
      REDIS_QUEUE_NAME: ${REDIS_QUEUE_NAME:-callback_queue}
      CALLBACK_ENABLED: ${CALLBACK_ENABLED:-true}
      CALLBACK_MAX_UPSTREAM_EVENTS: ${CALLBACK_MAX_UPSTREAM_EVENTS:-10}
      CALLBACK_MAX_RETRY_COUNT: ${CALLBACK_MAX_RETRY_COUNT:-10}
      CALLBACK_ENQUEUE_DELAY_SECONDS: ${CALLBACK_ENQUEUE_DELAY_SECONDS:-20}
      CALLBACK_TIMEOUT_SECONDS: ${CALLBACK_TIMEOUT_SECONDS:-10}
    depends_on:
      - redis
    command: 'uvicorn main:api --reload --port=8001 --host=0.0.0.0'
    ports:
      - "8001:8001"
    volumes:
      - .:/api/
